{% set name = "pangolin" %}
{% set version = "2024.07.03" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/stevenlovegrove/Pangolin.git
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ninja
    - cmake
    - pkg-config  
    # - sysroot_linux-64 2.17          # [linux64]
    - {{ cdt('libglvnd-egl') }}      # [linux]
    - {{ cdt('libglvnd-devel') }}    # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-libegl-devel') }} # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - xorg-libxext 
    - xorg-libx11 
    - xorg-libxfixes
  host:
    - epoxy
    - eigen
    - libpng
    - wayland
    - wayland-protocols  
    - libxkbcommon
  
about:
  home: https://github.com/stevenlovegrove/Pangolin.git
  license: MIT
  license_file: LICENCE
  summary: Pangolin - A set of lightweight and portable utility libraries for prototyping 3D, numeric or video based programs and algorithms.
  dev_url: https://github.com/stevenlovegrove/Pangolin.git
  doc_url: https://github.com/stevenlovegrove/Pangolin.git

extra:
  recipe-maintainers:
    - fontan
